=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/lib/documentManager/schemas/page.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "geometry": {
            "type": "object",
            "properties": {

                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "w": {
                    "type": "number"
                },
                "h": {
                    "type": "number"
                }
            },
            "required": ["x", "y", "w", "h"]
        },
        "docLocation": {
            "oneOf": [{
                "properties": {
                    "oId": {
                        "type": "string"
                    }
                },
                "required": ["oId"]
            }, {
                "properties": {
                    "path": {
                        "type": "string"
                    }
                },
                "required": ["path"]
            }]
        },
        "view": {
            "allOf": [{
                "$ref": "#/definitions/docLocation"
            }, {
                "properties": {
                    "geometry": {
                        "$ref": "#/definitions/geometry"
                    },
                    "windowState": {
                        "type": "string",
                        "default": "Normalized",
                        "enum": ["Minimized", "Normalized", "Maximized"]
                    }
                },
                "required": ["geometry", "windowState"]
            }]
        }
    },

    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "enum": ["Page"]
        },
        "hideBorders": {
            "type": "boolean",
            "default": false
        },
        "views": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/view"
            }
        },
        "title": {
            "type": "string"
        }
    },
    "required": ["type", "views", "title"]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/pages/pageCommande.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page Commande",
  "views": [
    {
      "path": "/views/viewTelecommande.json",
      "geometry": {
      "kind": "Relative",
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 12
      },
      "windowState": "Normalized"
    },
	{
	  "path": "/views/viewPointage.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 2,
		"w": 16,
		"h": 10
	  },
	  "windowState": "Normalized"
	},
  {
	  "path": "/views/viewGuidage.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 4,
		"w": 16,
		"h": 10
	  },
	  "windowState": "Normalized"
	}
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/pages/page3.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page example 3",
  "views": [
    {
      "path": "/views/text3.json",
      "geometry": {
      "kind": "Relative",
      "x": 8,
      "y": 4,
      "w": 4,
      "h": 16
      },
      "windowState": "Normalized"
    },
	{
	  "path": "/views/plot1.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 2,
		"w": 4,
		"h": 16
	  },
	  "windowState": "Normalized"
	},
  {
	  "path": "/views/plot3.json",
	  "geometry": {
		"kind": "Relative",
		"x": 4,
		"y": 6,
		"w": 4,
		"h": 16
	  },
	  "windowState": "Normalized"
	}
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/lib/documentsManager/examples/page01.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "showCase page",
  "views": [
    {
      "oId": "/views/plot1.view.json",
      "geometry": {
        "kind": "Relative",
        "x": 0,
        "y": 0,
        "w": 6,
        "h": 8
      },
      "windowState": "Normalized"
    },
    {
      "path": "/views/plot2.view.json",
      "geometry": {
        "kind": "Relative",
        "x": 7,
        "y": 0,
        "w": 6,
        "h": 8
      },
      "windowState": "Normalized"
    }
  ]
}

=== msadoq/project-js/GPCCHS_E_CLT/src/client/src/impl/js/client/data/page.exe3.workspace.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page example 3",
  "views": [
	{
	  "path": "/views/plot.exe1.workspace.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 0,
		"w": 12,
		"h": 7
	  },
	  "windowState": "Normalized"
	},
  {
	  "path": "/views/plot.exe2.workspace.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 0,
		"w": 12,
		"h": 7
	  },
	  "windowState": "Normalized"
	}
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/pages/pageSupsup.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page Sup/Sup workspace",
  "views": [
    {
      "path": "/views/plotviewSupsup_Test10.json",
      "geometry": {
        "kind": "Relative",
        "x": 4,
        "y": 0,
        "w": 4,
        "h": 14	
      },
      "windowState": "Normalized"
    },
{
      "path": "/views/plotviewSupsup.json",
      "geometry": {
        "kind": "Relative",
        "x": 0,
        "y": 0,
        "w": 4,
        "h": 14	
      },
      "windowState": "Normalized"
    },
    {
      "path": "/views/textviewSupsup.json",
      "geometry": {
        "kind": "Relative",
        "x": 8,
        "y": 0,
        "w": 4,
        "h": 14	
      },
      "windowState": "Normalized"
    }
  ]
}

=== msadoq/project-js/GPCCHS_E_CLT/src/client/src/impl/js/client/data/pages/page1Pbf.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page example PBF",
  "views": [
	{
	  "path": "./views/plot1pbf.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 2,
		"w": 4,
		"h": 16
	  },
	  "windowState": "Normalized"
	},
  {
	  "path": "./views/text1pbf.json",
	  "geometry": {
		"kind": "Relative",
		"x": 8,
		"y": 4,
		"w": 4,
		"h": 16
	  },
	  "windowState": "Normalized"
	},
  {
	  "path": "./views/text2pbf.json",
	  "geometry": {
		"kind": "Relative",
		"x": 4,
		"y": 6,
		"w": 4,
		"h": 16
	  },
	  "windowState": "Normalized"
	}
  ]
}

=== msadoq/project-js/GPCCHS_E_CLT/src/client/src/impl/js/client/app/documents/features/pages/showcase.page.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "showcase page",
  "views": [
    {
      "oId": "/views/plot1.view.json",
      "geometry": {
        "kind": "Relative",
        "x": 0,
        "y": 0,
        "w": 6,
        "h": 8
      },
      "windowState": "Normalized"
    },
    {
      "oId": "/views/text1.view.json",
      "geometry": {
        "kind": "Relative",
        "x": 0,
        "y": 9,
        "w": 4,
        "h": 8
      },
      "windowState": "Normalized"
    }
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/pages/pageLarge1.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page Large workspace 1",
  "views": [
    {
      "path": "/views/text100.json",
      "geometry": {
      "kind": "Relative",
      "x": 4,
      "y": 4,
      "w": 8,
      "h": 10
      },
      "windowState": "Normalized"
    },
	{
	  "path": "/views/plotview10.json",
	  "geometry": {
		"kind": "Relative",
		"x": 0,
		"y": 2,
		"w": 4,
		"h": 10
	  },
	  "windowState": "Normalized"
	},
  {
	  "path": "/views/text30.json",
	  "geometry": {
		"kind": "Relative",
		"x": 10,
		"y": 6,
		"w": 16,
		"h": 6
	  },
	  "windowState": "Normalized"
	}
  ]
}
