=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/lib/documentManager/schemas/page.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "geometry": {
            "type": "object",
            "properties": {

                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "w": {
                    "type": "number"
                },
                "h": {
                    "type": "number"
                }
            },
            "required": ["x", "y", "w", "h"]
        },
        "docLocation": {
            "oneOf": [{
                "properties": {
                    "oId": {
                        "type": "string"
                    }
                },
                "required": ["oId"]
            }, {
                "properties": {
                    "path": {
                        "type": "string"
                    }
                },
                "required": ["path"]
            }]
        },
        "view": {
            "allOf": [{
                "$ref": "#/definitions/docLocation"
            }, {
                "properties": {
                    "geometry": {
                        "$ref": "#/definitions/geometry"
                    },
                    "windowState": {
                        "type": "string",
                        "default": "Normalized",
                        "enum": ["Minimized", "Normalized", "Maximized"]
                    }
                },
                "required": ["geometry", "windowState"]
            }]
        }
    },

    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "enum": ["Page"]
        },
        "hideBorders": {
            "type": "boolean",
            "default": false
        },
        "views": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/view"
            }
        },
        "title": {
            "type": "string"
        }
    },
    "required": ["type", "views", "title"]
}

=== msadoq/project-js/GPCCHS_E_CLT/src/client/src/impl/js/client/app/documents/examples/PG.example.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "Page example",
  "views": [
    {
      "oId": "/VIMA_Demos/PV/PV.example.json",
      "geometry": {
        "kind": "Relative",
        "x": 5,
        "y": 5,
        "w": 45,
        "h": 50
      },
      "windowState": "Normalized"
    },
    {
      "path": "PV/PV.example.json",
      "geometry": {
        "kind": "Relative",
        "x": 50,
        "y": 5,
        "w": 45,
        "h": 50
      },
      "windowState": "Normalized"
    }
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/pages/pageTest.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "page Test workspace",
  "views": [
    {
      "path": "/views/textviewTest.json",
      "geometry": {
      "kind": "Relative",
      "x": 0,
      "y": 0,
      "w": 6,
      "h": 14
      },
      "windowState": "Normalized"
    },
    {
      "path": "/views/plotviewTest.json",
      "geometry": {
        "kind": "Relative",
        "x": 6,
        "y": 0,
        "w": 6,
        "h": 14
      },
      "windowState": "Normalized"
    }
  ]
}
