=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/lib/common/viewConfigurationFiles/schemas/v2.0/page.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "page.schema.json",
  "definitions": {
    "geometry": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "w": {
          "type": "number"
        },
        "h": {
          "type": "number"
        },
        "maxH": {
          "type": "number"
        },
        "maxW": {
          "type": "number"
        }
      },
      "required": [
        "x",
        "y",
        "w",
        "h"
      ]
    },
    "docLocation": {
      "oneOf": [
        {
          "properties": {
            "oId": {
              "type": "string"
            }
          },
          "required": [
            "oId"
          ]
        },
        {
          "properties": {
            "path": {
              "type": "string"
            }
          },
          "required": [
            "path"
          ]
        }
      ]
    },
    "view": {
      "allOf": [
        {
          "$ref": "#/definitions/docLocation"
        },
        {
          "properties": {
            "geometry": {
              "$ref": "#/definitions/geometry"
            },
            "windowState": {
              "type": "string",
              "default": "Normalized",
              "enum": [
                "Minimized",
                "Normalized",
                "Maximized"
              ]
            }
          },
          "required": [
            "geometry",
            "windowState"
          ]
        }
      ]
    }
  },
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "Page"
    },
    "hideBorders": {
      "type": "boolean",
      "default": false
    },
    "views": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/view"
      }
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "type",
    "views",
    "title"
  ],
  "additionalProperties": false
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/lib/documentManager/fixtures/pages/page1.json
{
  "type": "Page",
  "hideBorders": false,
  "title": "showCase page",
  "views": [
    {
      "oId": "oId:/views/plot1.json",
      "geometry": {
        "kind": "Relative",
        "x": 0,
        "y": 0,
        "w": 6,
        "h": 8
      },
      "windowState": "Normalized"
    },
    {
      "path": "/views/plot1.json",
      "geometry": {
        "kind": "Relative",
        "x": 7,
        "y": 0,
        "w": 6,
        "h": 8
      },
      "windowState": "Normalized"
    }
  ]
}
