=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/scripts/viewConfigurationFiles/schemas/v2.0/MimicView.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "titleStyle": {
      "type": "object",
      "properties": {
        "color": {
          "type": "string",
          "minLength": 1
        },
        "underline": {
          "type": "boolean"
        },
        "align": {
          "type": "string",
          "minLength": 1
        },
        "font": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "backgroundColor": {
      "type": "string",
      "minLength": 1
    },
    "links": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "defaultRatio": {
      "type": "object",
      "properties": {
        "length": {
          "type": "number"
        },
        "width": {
          "type": "number"
        }
      },
      "required": [
        "length",
        "width"
      ]
    },
    "content": {
      "type": "string",
      "minLength": 1
    },
    "entryPoints": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name"
        ],
        "properties": {
          "connectedData": {
            "type": "object",
            "properties": {
              "catalog": {
                "type": "string",
                "minLength": 1
              },
              "catalogItem": {
                "type": "string",
                "minLength": 1
              },
              "comObject": {
                "type": "string",
                "minLength": 1
              },
              "comObjectField": {
                "type": "string",
                "minLength": 1
              },
              "convertFrom": {
                "type": "string"
              },
              "convertTo": {
                "type": "string"
              },
              "digits": {
                "type": "number"
              },
              "domain": {
                "type": "string",
                "minLength": 1
              },
              "filter": {
                "type": "array",
                "items": {
                  "required": [],
                  "properties": {}
                }
              },
              "format": {
                "type": "string",
                "minLength": 1
              },
              "formula": {
                "type": "string",
                "minLength": 1
              },
              "provider": {
                "type": "string",
                "minLength": 1
              },
              "timeline": {
                "type": "string",
                "minLength": 1
              },
              "unit": {
                "type": "string"
              }
            },
            "required": [
              "digits",
              "domain",
              "format",
              "formula",
              "timeline",
              "unit"
            ]
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "stateColors": {
            "type": "array",
            "items": {
              "required": [],
              "properties": {}
            }
          }
        }
      }
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      "required": [
        "width",
        "height"
      ]
    }
  },
  "required": [
    "type",
    "content",
    "entryPoints"
  ],
  "additionalProperties": false
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/data/views/mimic_demo.json
{
  "type": "MimicView",
  "title": "MimicView - DEMO",
  "titleStyle": {
    "align": "center",
    "bgColor": "#795548",
    "color": "#FFF",
    "font": "Arial",
    "underline": true
  },
  "backgroundColor": "#ffffff",
  "links": [],
  "defaultRatio": {
    "length": 5,
    "width": 5
  },
  "content": "<!-- ---------------------------------------------- -->\n<!-- MULTISTATE SWITCH 6 STATES - |AGA_AM_PRIORITY| -->\n\n<g transform=\"translate(40,0)\">\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|117.5|#F8F8F8;;>=|117.5|#ffe8d3;;>|117.8|#F8F8F8\">\n    <rect width=\"200\" height=\"200\" style=\"fill:#F8F8F8;stroke:#CCC\" />\n  </g>\n  <text x=\"50\" y=\"26\" fill=\"#888\" style=\"font-size:12px;font-weight:bold;\">AGA_AM_PRIORITY</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|119.1|#FFF;;>=|119.1|#96ceaa\">\n    <circle cx=\"40\" cy=\"60\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"32\" y=\"86\" fill=\"#666\" style=\"font-size:11px\">St 1</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|117.5|#FFF;;>=|117.5|#96ceaa;;>|117.8|#FFF\">\n    <circle cx=\"100\" cy=\"60\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"92\" y=\"86\" fill=\"#666\" style=\"font-size:11px\">St 2</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|117.8|#FFF;;>=|117.8|#96ceaa;;>|118.1|#FFF\">\n    <circle cx=\"162\" cy=\"60\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"154\" y=\"86\" fill=\"#666\" style=\"font-size:11px\">St 3</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|118.1|#FFF;;>=|118.1|#96ceaa;;>|118.4|#FFF\">\n    <circle cx=\"40\" cy=\"120\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"32\" y=\"146\" fill=\"#666\" style=\"font-size:11px\">St 4</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|118.4|#FFF;;>=|118.4|#96ceaa;;>|118.8|#FFF\">\n    <circle cx=\"100\" cy=\"120\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"92\" y=\"146\" fill=\"#666\" style=\"font-size:11px\">St 5</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_color_operators=\"<|118.8|#FFF;;>=|118.8|#96ceaa;;>|119.1|#FFF\">\n    <circle cx=\"162\" cy=\"120\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"154\" y=\"146\" fill=\"#666\" style=\"font-size:11px\">St 6</text>\n\n  <text x=\"70\" y=\"180\" fill=\"#2a7bc5\" style=\"font-size:12px;cursor:pointer;\">Open in plot</text>\n</g>\n\n\n<!-- -------------------------------- -->\n<!-- 3 VERTICAL GAUGES - |AGA_AM_QP2| -->\n\n<g transform=\"translate(260,0)\">\n  <rect width=\"200\" height=\"200\" style=\"fill:#F8F8F8;stroke:#CCC\" />\n  <text x=\"60\" y=\"26\" fill=\"#888\" style=\"font-size:12px;font-weight:bold;\">AGA_AM_QP2</text>\n\n  <path d=\"M30,46 l22,0 l0,110 l-22,0 z\" style=\" fill:#DDD\" />\n  <g isis_animation=\"scaleY\" isis_ep=\"AGA_AM_QP2\" isis_domain=\"74,78\" isis_origin=\"center,bottom\" isis_scale=\"0,100\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_QP2\" isis_operators=\"\">\n      <path d=\"M30,46 l22,0 l0,110 l-22,0 z\" style=\" fill:#96ceaa\" />\n    </g>\n  </g>\n  <g isis_animation=\"translateY\" isis_ep=\"AGA_AM_QP2\" isis_domain=\"74,78\" isis_distance=\"110\" isis_direction=\"top\">\n    <path d=\"M27,156 l0,2 l28,0 l0,-2 z\" style=\" fill: #666\" />\n  </g>\n\n  <path d=\"M88,46 l22,0 l0,110 l-22,0 z\" style=\" fill:#DDD\" />\n  <g isis_animation=\"scaleY\" isis_ep=\"AGA_AM_QP2\" isis_domain=\"74.4,76.4\" isis_origin=\"center,bottom\" isis_scale=\"0,100\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_QP2\" isis_color_operators=\"<=|76.1|#96ceaa;;>|76.1|#FDE47F;;>=|76.3|#c34c23\">\n      <path d=\"M88,46 l22,0 l0,110 l-22,0 z\" style=\" fill:#96ceaa\" />\n    </g>\n  </g>\n  <g isis_animation=\"translateY\" isis_ep=\"AGA_AM_QP2\" isis_domain=\"74.4,76.4\" isis_distance=\"110\" isis_direction=\"top\">\n    <path d=\"M85,156 l0,2 l28,0 l0,-2 z\" style=\" fill: #666\" />\n  </g>\n\n  <path d=\"M146,46 l22,0 l0,110 l-22,0 z\" style=\" fill:#DDD\" />\n  <g isis_animation=\"scaleY\" isis_ep=\"AGA_AM_QP2\" isis_domain=\"74,77\" isis_origin=\"center,bottom\" isis_scale=\"0,100\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_QP2\" isis_operators=\"<=$118$#96ceaa*>$118$#78a388\">\n      <path d=\"M146,46 l22,0 l0,110 l-22,0 z\" style=\" fill:#96ceaa\" />\n    </g>\n  </g>\n  <g isis_animation=\"translateY\" isis_ep=\"AGA_AM_QP2\" isis_domain=\"74,77\" isis_distance=\"110\" isis_direction=\"top\">\n    <path d=\"M143,156 l0,2 l28,0 l0,-2 z\" style=\" fill: #666\" />\n  </g>\n\n  <text x=\"70\" y=\"180\" fill=\"#2a7bc5\" style=\"font-size:12px;cursor:pointer;\">Open in plot</text>\n</g>\n\n\n<!-- --------------------------------------- -->\n<!-- 3 HORIZONTAL SLIDERS - |AGA_AM_VALMASK| -->\n\n<g transform=\"translate(480,0)\">\n  <rect width=\"200\" height=\"200\" style=\"fill:#F8F8F8;stroke:#CCC\" />\n  <text x=\"44\" y=\"26\" fill=\"#888\" style=\"font-size:12px;font-weight:bold;\">AGA_AM_VALMASK</text>\n  \n  <path d=\"M30,56 l140,0 l0,6 l-140,0 z\" style=\" fill: #DDD; stroke: #BBB;\" />\n  <g isis_animation=\"translateX\" isis_ep=\"AGA_AM_VALMASK\" isis_domain=\"106,110\" isis_distance=\"140\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_VALMASK\" isis_color_thresholds=\"<=|118|#EEE;;>|118|#F70;;>|119|#F11\">\n      <ellipse cx=\"30\" cy=\"59\" rx=\"8\" ry=\"8\" style=\"fill: #F8F8F8; stroke: #BBB;\" />\n    </g>\n  </g>\n  \n  <path d=\"M30,96 l140,0 l0,6 l-140,0 z\" style=\" fill: #DDD; stroke: #BBB;\" />\n  <g isis_animation=\"translateX\" isis_ep=\"AGA_AM_VALMASK\" isis_domain=\"106,108\" isis_distance=\"140\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_VALMASK\" isis_color_thresholds=\"<=|118|#EEE;;>|118|#F70;;>|119|#F11\">\n      <ellipse cx=\"30\" cy=\"99\" rx=\"8\" ry=\"8\" style=\"fill: #F8F8F8; stroke: #BBB;\" />\n    </g>\n  </g>\n  \n  <path d=\"M30,136 l140,0 l0,6 l-140,0 z\" style=\" fill: #DDD; stroke: #BBB;\" />\n  <g isis_animation=\"translateX\" isis_ep=\"AGA_AM_VALMASK\" isis_domain=\"106,109\" isis_distance=\"140\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_VALMASK\" isis_color_thresholds=\"<=|118|#EEE;;>|118|#F70;;>|119|#F11\">\n      <ellipse cx=\"30\" cy=\"139\" rx=\"8\" ry=\"8\" style=\"fill: #F8F8F8; stroke: #BBB;\" />\n    </g>\n  </g>\n  \n  <text x=\"70\" y=\"180\" fill=\"#2a7bc5\" style=\"font-size:12px;cursor:pointer;\">Open in plot</text>\n\n</g>\n\n\n<!-- --------------------------------------------------------------------- -->\n<!-- 1 HORIZONTAL GAUGE + MULTISTATE SWITCH 3 STATES - |ATT_BC_QUATSATREF| -->\n\n<g transform=\"translate(700,0)\">\n  <rect width=\"200\" height=\"200\" style=\"fill:#F8F8F8;stroke:#CCC\" />\n  <text x=\"44\" y=\"26\" fill=\"#888\" style=\"font-size:12px;font-weight:bold;\">ATT_BC_QUATSATREF</text>\n  \n  <path d=\"M20,66 l160,0 l0,22 l-160,0 z\" style=\" fill:#DDD\" />\n  <g isis_animation=\"scaleX\" isis_ep=\"ATT_BC_QUATSATREF\" isis_domain=\"132.4,134.4\" isis_scale=\"0,100\">\n    <g isis_animation=\"colour\" isis_ep=\"ATT_BC_QUATSATREF\" isis_color_operators=\"<=|133|#9eafd4;;>|133|#8b9dc3;;>|133.8|#637db2\">\n      <path d=\"M20,66 l160,0 l0,22 l-160,0 z\" style=\" fill:#dfe3ee\" />\n    </g>\n  </g>\n  <g isis_animation=\"translateX\" isis_ep=\"ATT_BC_QUATSATREF\" isis_domain=\"132.4,134.4\" isis_distance=\"160\" isis_direction=\"right\">\n    <path d=\"M19,62 l2,0 l0,30 l-2,0 z\" style=\" fill: #666\" />\n  </g>\n  <text x=\"20\" y=\"56\" fill=\"#666\" style=\"font-size:10px\">132.4</text>\n  <text x=\"152\" y=\"56\" fill=\"#666\" style=\"font-size:10px\">134.4</text>\n  <g isis_x=\"80\" isis_y=\"81\" isis_animation=\"textBox\" isis_ep=\"ATT_BC_QUATSATREF\" isis_textcolor=\"0$#FFF\">-</g>\n  \n   <g isis_animation=\"colour\" isis_ep=\"ATT_BC_QUATSATREF\" isis_color_operators=\"<=|133|#637db2;;>|133|#FFF\">\n    <circle cx=\"40\" cy=\"120\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"32\" y=\"146\" fill=\"#666\" style=\"font-size:11px\">St 1</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"ATT_BC_QUATSATREF\" isis_color_operators=\"<=|133|#FFF;;>|133|#637db2;;>|133.8|#FFF\">\n    <circle cx=\"100\" cy=\"120\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"92\" y=\"146\" fill=\"#666\" style=\"font-size:11px\">St 2</text>\n\n  <g isis_animation=\"colour\" isis_ep=\"ATT_BC_QUATSATREF\" isis_color_operators=\"<|133.8|#FFF;;>=|133.8|#637db2\">\n    <circle cx=\"162\" cy=\"120\" r=\"8\" stroke=\"#444\" stroke-width=\"2\" fill=\"#FFF\" />\n  </g>\n  <text x=\"154\" y=\"146\" fill=\"#666\" style=\"font-size:11px\">St 3</text>\n  \n   <text x=\"70\" y=\"180\" fill=\"#2a7bc5\" style=\"font-size:12px;cursor:pointer;\">Open in plot</text>\n</g>\n\n\n<!-- ----------------------------- -->\n<!-- 1 KNOBE - |GENE_AM_144PARINT| -->\n\n<g transform=\"translate(40,220)\">\n  <rect width=\"200\" height=\"200\" style=\"fill:#F8F8F8;stroke:#CCC\" />\n  <text x=\"44\" y=\"26\" fill=\"#888\" style=\"font-size:12px;font-weight:bold;\">GENE_AM_144PARINT</text>\n    \n  <circle r=\"54\" cx=\"100\" cy=\"105\" stroke=\"#FDE47F\" transform=\"rotate(126, 100, 105)\" stroke-width=\"8\" fill=\"none\" stroke-dasharray=\"272\"></circle>\n  <g isis_animation='rotate' isis_ep='AGA_AM_PRIORITY' isis_domain='117,121' isis_angle='-138,138' isis_origin='center,bottom'>\n    <path d=\"M100,65 l6,40 q-5,5 -10,0 z\" style=\"fill: #666\" />\n  </g>\n  <text x=\"30\" y=\"154\" fill=\"#999\" style=\"font-weight:bold;font-size:11px\">117</text>\n  <text x=\"150\" y=\"154\" fill=\"#999\" style=\"font-weight:bold;font-size:11px\">121</text>\n  <text x=\"70\" y=\"180
