=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/scripts/viewConfigurationFiles/schemas/v2.0/page.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "minLength": 1
    },
    "hideBorders": {
      "type": "boolean"
    },
    "timebarHeight": {
      "type": "number"
    },
    "timebarCollapsed": {
      "type": "boolean"
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "sessionName": {
      "type": "string",
      "minLength": 1
    },
    "domainName": {
      "type": "string",
      "minLength": 1
    },
    "views": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "windowState"
        ],
        "properties": {
          "oId": {
            "type": "string",
            "minLength": 1
          },
          "path": {
            "type": "string",
            "minLength": 1
          },
          "geometry": {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string"
              },
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "w": {
                "type": "number"
              },
              "h": {
                "type": "number"
              },
              "maxH": {
                "type": "number"
              },
              "maxW": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y",
              "w",
              "h"
            ]
          },
          "hideBorders": {
            "type": "boolean"
          },
          "windowState": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    }
  },
  "required": [
    "type",
    "title",
    "views"
  ],
  "additionalProperties": false
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/pages/dev.page2.json
{
  "type": "Page",
  "hideBorders": false,
  "timebarHeight": 140,
  "timebarCollapsed": false,
  "title": "FMD page",
  "views": [
    {
      "oId": "oid:views/text30.json",
      "geometry": {
      "kind": "Relative",
      "x": 0,
      "y": 0,
      "w": 6,
      "h": 14
      },
      "windowState": "Normalized"
    },
    {
      "oId": "oid:views/plotview4.json",
      "geometry": {
        "kind": "Relative",
        "x": 6,
        "y": 0,
        "w": 6,
        "h": 14
      },
      "windowState": "Normalized"
    }
  ]
}
