=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/scripts/viewConfigurationFiles/schemas/v2.0/PlotView.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "titleStyle": {
      "type": "object",
      "properties": {
        "align": {
          "type": "string",
          "minLength": 1
        },
        "bold": {
          "type": "boolean"
        },
        "font": {
          "type": "string",
          "minLength": 1
        },
        "italic": {
          "type": "boolean"
        },
        "size": {
          "type": "number"
        },
        "strikeOut": {
          "type": "boolean"
        },
        "underline": {
          "type": "boolean"
        }
      },
      "required": [
        "align",
        "bold",
        "font",
        "italic",
        "size",
        "strikeOut",
        "underline"
      ]
    },
    "backgroundColor": {
      "type": "string",
      "minLength": 1
    },
    "links": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name",
          "path"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "path": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "defaultRatio": {
      "type": "object",
      "properties": {
        "length": {
          "type": "number"
        },
        "width": {
          "type": "number"
        }
      },
      "required": [
        "length",
        "width"
      ]
    },
    "procedures": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "axes": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "properties": {
          "label": {
            "type": "string",
            "minLength": 1
          },
          "id": {
            "type": "string",
            "minLength": 1
          },
          "unit": {
            "type": "string",
            "minLength": 1
          },
          "style": {
            "type": "object",
            "properties": {
              "font": {
                "type": "string",
                "minLength": 1
              },
              "size": {
                "type": "number"
              },
              "bold": {
                "type": "boolean"
              },
              "italic": {
                "type": "boolean"
              },
              "underline": {
                "type": "boolean"
              },
              "strikeOut": {
                "type": "boolean"
              },
              "align": {
                "type": "string",
                "minLength": 1
              },
              "color": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "font",
              "size",
              "bold",
              "italic",
              "underline",
              "strikeOut",
              "align",
              "color"
            ]
          },
          "min": {
            "type": "number"
          },
          "max": {
            "type": "number"
          },
          "autoLimits": {
            "type": "boolean"
          },
          "tickStep": {
            "type": "number"
          },
          "autoTick": {
            "type": "boolean"
          },
          "showTicks": {
            "type": "boolean"
          },
          "showTickLabels": {
            "type": "boolean"
          },
          "logarithmic": {
            "type": "boolean"
          },
          "logSettings": {
            "type": "object",
            "properties": {
              "min": {
                "type": "number"
              },
              "max": {
                "type": "number"
              },
              "base": {
                "type": "number"
              }
            },
            "required": [
              "min",
              "max",
              "base"
            ]
          },
          "showAxis": {
            "type": "boolean"
          },
          "showLabels": {
            "type": "boolean"
          }
        }
      }
    },
    "grids": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "showGrid",
          "xAxisId",
          "yAxisId"
        ],
        "properties": {
          "showGrid": {
            "type": "boolean"
          },
          "line": {
            "type": "object",
            "properties": {
              "size": {
                "type": "number"
              },
              "style": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "size",
              "style"
            ]
          },
          "xAxisId": {
            "type": "string",
            "minLength": 1
          },
          "yAxisId": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "legend": {
      "type": "object",
      "properties": {
        "location": {
          "type": "string",
          "minLength": 1
        },
        "style": {
          "type": "object",
          "properties": {
            "font": {
              "type": "string",
              "minLength": 1
            },
            "size": {
              "type": "number"
            },
            "bold": {
              "type": "boolean"
            },
            "italic": {
              "type": "boolean"
            },
            "underline": {
              "type": "boolean"
            },
            "strikeOut": {
              "type": "boolean"
            },
            "align": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "font",
            "size",
            "bold",
            "italic",
            "underline",
            "strikeOut",
            "align",
            "color"
          ]
        }
      },
      "required": [
        "location",
        "style"
      ]
    },
    "markers": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "kind",
          "label",
          "relativePosX",
          "relativePosY"
        ],
        "properties": {
          "kind": {
            "type": "string",
            "minLength": 1
          },
          "label": {
            "type": "string",
            "minLength": 1
          },
          "style": {
            "type": "object",
            "properties": {
              "font": {
                "type": "string",
                "minLength": 1
              },
              "size": {
                "type": "number"
              },
              "bold": {
                "type": "boolean"
              },
              "italic": {
                "type": "boolean"
              },
              "underline": {
                "type": "boolean"
              },
              "strikeOut": {
                "type": "boolean"
              },
              "align": {
                "type": "string",
                "minLength": 1
              },
              "color": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "font",
              "size",
              "bold",
              "italic",
              "underline",
              "strikeOut",
              "align",
              "color"
            ]
          },
          "relativePosX": {
            "type": "number"
          },
          "relativePosY": {
            "type": "number"
          }
        }
      }
    },
    "entryPoints": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name"
        ],
        "properties": {
          "connectedData": {
            "type": "object",
            "properties": {
              "axisId": {
                "type": "string",
                "minLength": 1
              },
              "catalog": {
                "type": "string",
                "minLength": 1
              },
              "catalogItem": {
                "type": "string",
                "minLength": 1
              },
              "comObject": {
                "type": "string",
                "minLength": 1
              },
              "comObjectField": {
                "type": "string",
                "minLength": 1
              },
              "convertFrom": {
                "type": "string"
              },
              "convertTo": {
                "type": "string"
              },
              "defaultY": {
                "type": "number"
              },
              "digits": {
                "type": "number"
              },
              "domain": {
                "type": "string",
                "minLength": 1
              },
              "fieldX": {
                "type": "string",
                "minLength": 1
              },
              "filter": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "required": [
                    "field",
                    "operand",
                    "operator"
                  ],
                  "properties": {
                    "field": {
                      "type": "string",
                      "minLength": 1
                    },
                    "operand": {
                      "type": "string",
                      "minLength": 1
                    },
                    "operator": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "format": {
                "type": "string",
                "minLength": 1
              },
              "formula": {
                "type": "string",
                "minLength": 1
              },
              "provider": {
                "type": "string",
                "minLength": 1
              },
              "stringParameter": {
                "type": "boolean"
              },
              "timeline": {
                "type": "string",
                "minLength": 1
              },
              "unit": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "digits",
              "domain",
              "fieldX",
              "format",
              "formula",
              "provider",
              "stringParameter",
              "timeline",
              "unit"
            ]
          },
          "connectedDataParametric": {
            "type": "object",
            "properties": {
              "domainX": {
                "type": "string"
              },
              "domainY": {
                "type": "string"
              },
              "formulaX": {
                "type": "string"
              },
              "formulaY": {
                "type": "string"
              },
              "unitX": {
                "type": "string"
              },
              "unitY": {
                "type": "string"
              },
              "xAxisId": {
                "type": "string"
              },
              "yAxisId": {
                "type": "string"
              }
            },
            "required": [
              "domainX",
              "domainY",
              "formulaX",
              "formulaY",
              "unitX",
              "unitY",
              "xAxisId",
              "yAxisId"
            ]
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "objectStyle": {
            "type": "object",
            "properties": {
              "curveColor": {
                "type": "string",
                "minLength": 1
              },
              "line": {
                "type": "object",
                "properties": {
                  "size": {
                    "type": "number"
                  },
                  "style": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "size",
                  "style"
                ]
              },
              "points": {
                "type": "object",
                "properties": {
                  "size": {
                    "type": "number"
                  },
                  "style": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "size",
                  "style"
                ]
              }
            },
            "required": [
              "curveColor",
              "line",
              "points"
            ]
          },
          "parametric": {
            "type": "boolean"
          },
          "stateColors": {
            "type": "array",
            "items": {
              "required": [],
              "properties": {}
            }
          }
        }
      }
    },
    "showYAxes": {
      "type": "string",
      "minLength": 1
    },
    "showLegend": {
      "type": "boolean"
    },
    "search": {
      "type": "string"
    }
  },
  "required": [
    "type",
    "title"
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/impl/js/client/data/views/plot.json
{
  "type": "PlotView",
  "links": [
    {
      "name": "page4",
      "path": "./pages/page4.json"
    }
  ],
  "procedures": [],
  "defaultRatio": {
    "length": 50,
    "width": 50
  },
  "entryPoints": [
    {
      "name": "TMMGT_BC_VIRTCHAN3",
      "connectedDataX": {
        "formula": "Reporting.TMMGT_BC_VIRTCHAN3<ReportingParameter>.groundDate",
        "unit": "s",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1",
        "axisId": "Time"
      },
      "connectedDataY": {
        "formula": "Reporting.TMMGT_BC_VIRTCHAN3<ReportingParameter>.extractedValue",
        "unit": "V",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1",
        "axisId": "VBat"
      },
      "objectStyle": {
        "line": {
          "style": "Continuous",
          "size": 2
        },
        "points": {
          "style": "None",
          "size": 0
        },
        "curveColor": "#FFBF00"
      },
      "stateColors": [
        {
          "color": "#000000",
          "condition": {
            "field": "monitoringState",
            "operator": "==",
            "operand": "waiting"
          }
        }
      ]
    },
    {
      "name": "ATT_BC_REVTCOUNT1",
      "connectedDataX": {
        "formula": "Reporting.ATT_BC_REVTCOUNT1<ReportingParameter>.groundDate",
        "unit": "s",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cne",
        "timeline": "Session 1",
        "axisId": "Time"
      },
      "connectedDataY": {
        "formula": "Reporting.ATT_BC_REVTCOUNT1<ReportingParameter>.extractedValue",
        "unit": "V",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis",
        "timeline": "Session 1",
        "axisId": "att_bc_revtcount_1_1"
      },
      "objectStyle": {
        "line": {
          "style": "Continuous",
          "size": 3
        },
        "points": {
          "style": "None",
          "size": 3
        },
        "curveColor": "#ff9800"
      },
      "stateColors": []
    }
  ],
  "axes": [
    {
      "label": "Time",
      "unit": "s",
      "style": {
        "font": "Arial",
        "size": 12,
        "bold": false,
        "italic": false,
        "underline": false,
        "strikeOut": false,
        "align": "left",
        "color": "#000000"
      },
      "min": 0,
      "max": 10,
      "autoLimits": true,
      "tickStep": 0.5,
      "autoTick": true,
      "showTicks": true,
      "showTickLabels": true,
      "isLogarithmic": false,
      "showAxis": true
    },
    {
      "label": "VBat",
      "unit": "V",
      "style": {
        "font": "Arial",
        "size": 12,
        "bold": false,
        "italic": false,
        "underline": false,
        "strikeOut": false,
        "align": "left",
        "color": "#000000"
      },
      "min": -300,
      "max": 300,
      "autoLimits": false,
      "tickStep": 50,
      "autoTick": false,
      "showTicks": true,
      "showTickLabels": true,
      "isLogarithmic": false,
      "showAxis": true
    },
    {
      "label": "ATT_BC_REVTCOUNT1",
      "unit": "s",
      "id": "att_bc_revtcount_1"
    },
    {
      "label": "ATT_BC_REVTCOUNT1",
      "unit": "V",
      "id": "att_bc_revtcount_1_1"
    }
  ],
  "grids": [
    {
      "xAxisId": "Time",
      "yAxisId": "VBat",
      "line": {
        "style": "Continuous",
        "size": 1
      },
      "showGrid": true
    }
  ],
  "title": "Plotview One parameter",
  "titleStyle": {
    "font": "Arial",
    "size": 12,
    "bold": false,
    "italic": false,
    "underline": true,
    "strikeOut": false,
    "align": "center",
    "color": "#000000"
  },
  "backgroundColor": "#FFFFFF",
  "showYAxes": "left",
  "legend": {
    "style": {
      "font": "Arial",
      "size": 12,
      "bold": false,
      "italic": false,
      "underline": false,
      "strikeOut": false,
      "align": "left",
      "color": "#000000"
    },
    "location": "top"
  },
  "markers": [
    {
      "kind": "Text",
      "label": "VBAT",
      "style": {
        "font": "Arial",
        "size": 12,
        "bold": false,
        "italic": false,
        "underline": true,
        "strikeOut": false,
        "align": "left",
        "color": "#000000"
      },
      "relativePosX": 5.6,
      "relativePosY": 8.9
    }
  ]
}
