=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/scripts/viewConfigurationFiles/schemas/v2.0/TextView.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "titleStyle": {
      "type": "object",
      "properties": {
        "font": {
          "type": "string",
          "minLength": 1
        },
        "size": {
          "type": "number"
        },
        "bold": {
          "type": "boolean"
        },
        "italic": {
          "type": "boolean"
        },
        "underline": {
          "type": "boolean"
        },
        "strikeOut": {
          "type": "boolean"
        },
        "align": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "links": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name",
          "path"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "path": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "defaultRatio": {
      "type": "object",
      "properties": {
        "length": {
          "type": "number"
        },
        "width": {
          "type": "number"
        }
      },
      "required": [
        "length",
        "width"
      ]
    },
    "content": {
      "type": "string",
      "minLength": 1
    },
    "entryPoints": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name"
        ],
        "properties": {
          "connectedData": {
            "type": "object",
            "properties": {
              "convertFrom": {
                "type": "string"
              },
              "convertTo": {
                "type": "string"
              },
              "digits": {
                "type": "number"
              },
              "domain": {
                "type": "string",
                "minLength": 1
              },
              "filter": {
                "type": "array",
                "items": {
                  "required": [],
                  "properties": {}
                }
              },
              "format": {
                "type": "string"
              },
              "formula": {
                "type": "string",
                "minLength": 1
              },
              "provider": {
                "type": "string",
                "minLength": 1
              },
              "timeline": {
                "type": "string",
                "minLength": 1
              },
              "unit": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "digits",
              "domain",
              "format",
              "formula",
              "timeline",
              "unit"
            ]
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "stateColors": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
              "required": [
                "color"
              ],
              "properties": {
                "color": {
                  "type": "string",
                  "minLength": 1
                },
                "condition": {
                  "type": "object",
                  "properties": {
                    "field": {
                      "type": "string"
                    },
                    "operand": {
                      "type": "string",
                      "minLength": 1
                    },
                    "operator": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "field",
                    "operand",
                    "operator"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "search": {
      "type": "string"
    }
  },
  "required": [
    "type",
    "content",
    "entryPoints"
  ]
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/data/views/text10.json
{
  "title": "TextView 100 parameters",
  "type": "TextView",
  "entryPoints": [
    {
      "name": "AGA_AM_ACQPRIORITY",
      "connectedData": {
        "formula": "Reporting.AGA_AM_ACQPRIORITY<ReportingParameter>.convertedValue",
        "unit": "V",
        "digits": 8,
        "format": "",
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1"
      }
    },

    {
          "name": "AGA_AM_CCSDSAPID",
          "connectedData": {
            "formula": "Reporting.AGA_AM_CCSDSAPID<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_CCSDSDATA",
          "connectedData": {
            "formula": "Reporting.AGA_AM_CCSDSDATA<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_CCSDSFLAG",
          "connectedData": {
            "formula": "Reporting.AGA_AM_CCSDSFLAG<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_CCSDSSEQU",
          "connectedData": {
            "formula": "Reporting.AGA_AM_CCSDSSEQU<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_CCSDSTYPE",
          "connectedData": {
            "formula": "Reporting.AGA_AM_CCSDSTYPE<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_CCSDSVERS",
          "connectedData": {
            "formula": "Reporting.AGA_AM_CCSDSVERS<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_ENABLED",
          "connectedData": {
            "formula": "Reporting.AGA_AM_ENABLED<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_FID",
          "connectedData": {
            "formula": "Reporting.AGA_AM_FID<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    },

    {
          "name": "AGA_AM_FIDCHKSTATUS",
          "connectedData": {
            "formula": "Reporting.AGA_AM_FIDCHKSTATUS<ReportingParameter>.convertedValue",
            "unit": "V",
            "digits": 8,
            "format": "",
            "domain": "fr.cnes.isis.simupus",
            "timeline": "Session 1"
        }
    }
  ],
  "links": [
    {
      "name": "page.exe2.workspace",
      "path": "../page.exe2.workspace.json"
    }
  ],
  "defaultRatio": {
    "length": 5,
    "width": 3
  },
  "content": "<style>  .myTextView {float: left; font-size: 1.2rem; }  .myTextView .myContener { background-color: #0f1051; margin-top: 4px; margin-left: 6px; padding:2px; float: left; border-radius: 1px; border: 1px ridge #0f0041; height: 51px; width: 180px; }  .myContener .name {display: block;  overflow: hidden; background-color: white; color: black; font-weight: bolder; font-size: 11px; padding: 2px; text-align: center;}  .myContener .value { text-align: center; display: block; overflow: hidden; background-color: #0f0041; color: #00ff00; font-weight: bold; padding: 10px; margin-bottom: 10px; }</style><div class='myTextView'><div class='myContener'><span class='name'>AGA_AM_ACQPRIORITY</span><span class='value'>{{AGA_AM_ACQPRIORITY}}</span></div> <div class='myContener'><span class='name'>AGA_AM_CCSDSAPID</span><span class='value'>{{AGA_AM_CCSDSAPID}}</span></div> <div class='myContener'><span class='name'>AGA_AM_CCSDSDATA</span><span class='value'>{{AGA_AM_CCSDSDATA}}</span></div> <div class='myContener'><span class='name'>AGA_AM_CCSDSFLAG</span><span class='value'>{{AGA_AM_CCSDSFLAG}}</span></div> <div class='myContener'><span class='name'>AGA_AM_CCSDSSEQU</span><span class='value'>{{AGA_AM_CCSDSSEQU}}</span></div> <div class='myContener'><span class='name'>AGA_AM_CCSDSTYPE</span><span class='value'>{{AGA_AM_CCSDSTYPE}}</span></div> <div class='myContener'><span class='name'>AGA_AM_CCSDSVERS</span><span class='value'>{{AGA_AM_CCSDSVERS}}</span></div> <div class='myContener'><span class='name'>AGA_AM_ENABLED</span><span class='value'>{{AGA_AM_ENABLED}}</span></div> <div class='myContener'><span class='name'>AGA_AM_FID</span><span class='value'>{{AGA_AM_FID}}</span></div> <div class='myContener'><span class='name'>AGA_AM_FIDCHKSTATUS</span><span class='value'>{{AGA_AM_FIDCHKSTATUS}}</span></div></div>"
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/data/views/text.json
{
  "type": "TextView",
  "title": "New Text View",
  "titleStyle": {
    "font": "Arial",
    "size": 12,
    "bold": false,
    "italic": false,
    "underline": true,
    "strikeOut": false,
    "align": "center",
    "color": "#ffffff",
    "bgColor": "#3F51B5"
  },
  "links": [
    {
      "name": "page.exe2.workspace",
      "path": "../page.exe2.workspace.json"
    }
  ],
  "defaultRatio": {
    "length": 5,
    "width": 5
  },
  "content": "<style>  .myTextView {float: left; font-size: 1.2rem; }  .myTextView .myContener { background-color: #0f1051; margin-top: 4px; margin-left: 6px; padding:2px; float: left; border-radius: 1px; border: 1px ridge #0f0041; height: 51px; width: 180px; }  .myContener .name {display: block;  overflow: hidden; background-color: white; color: black; font-weight: bolder; font-size: 11px; padding: 2px; text-align: center;}  .myContener .value { text-align: center; display: block; overflow: hidden; background-color: #0f0041; color: #00ff00; font-weight: bold; padding: 10px; margin-bottom: 10px; }</style><div class='myTextView'>    <div class='myContener'><span class='name'>AGA_AM_PRIORITY</span><span class='value'>{{AGA_AM_PRIORITY}}</span></div>    <div class='myContener'><span class='name'>TMMGT_BC_VIRTCHAN3</span><span class='value'>{{TMMGT_BC_VIRTCHAN3}}</span></div></div>",
  "entryPoints": [
    {
      "name": "AGA_AM_PRIORITY",
      "connectedData": {
        "formula": "Reporting.AGA_AM_PRIORITY<ReportingParameter>.extractedValue",
        "unit": "V",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1"
      }
    },
    {
      "name": "TMMGT_BC_VIRTCHAN3",
      "connectedData": {
        "formula": "Reporting.TMMGT_BC_VIRTCHAN3<ReportingParameter>.extractedValue",
        "unit": "V",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1"
      }
    },
    {
      "name": "Toto",
      "connectedData": {
        "formula": "",
        "unit": "s",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "*",
        "timeline": "*"
      }
    }
  ],
  "search": ""
}

=== msadoq/project-js/GPCCHS_E_VIS/src/client/src/main/js/client/data/views/mimic.json
{
  "type": "MimicView",
  "title": "New Mimic View",
  "titleStyle": {
    "color": "#FFF",
    "underline": true,
    "bgColor": "#2196f3",
    "align": "center"
  },
  "links": [],
  "defaultRatio": {
    "length": 5,
    "width": 5
  },
  "content": "<!-- HORIZONTAL GAUGE -->\n<g transform=\"translate(120,50)\">\n  <path d=\"M1,16 l200,0 l0,24 l-200,0 z\" style=\" fill:#DDD\" />\n  <g isis_animation=\"scaleX\" isis_ep=\"AGA_AM_PRIORITY\" isis_domain=\"117,120\" isis_fixed=\"left\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_operators=\"<=$118$#ddb065*>$118$#b8835e\">\n      <path d=\"M1,16 l200,0 l0,24 l-200,0 z\" style=\" fill:#ddb065\" />\n    </g>\n  </g>\n  <g isis_animation=\"translateX\" isis_ep=\"AGA_AM_PRIORITY\" isis_domain=\"117,120\" isis_width=\"200\" isis_direction=\"right\">\n    <path d=\"M0,13 l3,0 l0,30 l-3,0 z\" style=\" fill: #666\" />\n  </g>\n  <text x=\"0\" y=\"4\" fill=\"#666\" style=\"font-size:10px\">117</text>\n  <text x=\"184\" y=\"4\" fill=\"#666\" style=\"font-size:10px\">120</text>\n  <text x=\"52\" y=\"4\" fill=\"#666\" style=\"font-weight:bold;font-size:11px;\">AGA_AM_PRIORITY</text>\n  <g isis_x=\"90\" isis_y=\"32\" isis_animation=\"textBox\" isis_ep=\"AGA_AM_PRIORITY\" isis_textcolor=\"0$#FFF\">-</g>\n</g>\n\n\n<!-- VERTICAL GAUGE -->\n<g transform=\"translate(40,30)\">\n  <path d=\"M26,1 l24,0 l0,200 l-24,0 z\" style=\" fill:#DDD\" />\n  <g isis_animation=\"scaleY\" isis_ep=\"AGA_AM_PRIORITY\" isis_domain=\"117,120\" isis_fixed=\"bottom\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_operators=\"<=$118$#96ceaa*>$118$#78a388\">\n      <path d=\"M26,1 l24,0 l0,200 l-24,0 z\" style=\" fill:#96ceaa\" />\n    </g>\n  </g>\n  <g isis_animation=\"translateY\" isis_ep=\"AGA_AM_PRIORITY\" isis_domain=\"117,120\" isis_width=\"200\" isis_direction=\"top\">\n    <path d=\"M23,198 l0,3 l30,0 l0,-3 z\" style=\" fill: #666\" />\n  </g>\n  <text x=\"0\" y=\"200\" fill=\"#666\" style=\"font-size:10px\">117</text>\n  <text x=\"0\" y=\"6\" fill=\"#666\" style=\"font-size:10px\">120</text>\n  <text x=\"12\" y=\"150\" fill=\"#666\" style=\"font-weight:bold;font-size:11px;\" transform=\"rotate(-90, 12, 150)\">AGA_AM_PRIORITY</text>\n</g>\n\n\n<!-- HORIZONTAL SLIDER -->\n<g transform=\"translate(220,140)\">\n  <path d=\"M10,10 l200,0 l0,6 l-200,0 z\" style=\" fill: #DDD; stroke: #BBB;\" />\n  <g isis_animation=\"translateX\" isis_ep=\"AGA_AM_PRIORITY\" isis_domain=\"117,120\" isis_width=\"200\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_operators=\"<=$118$#EEE*>$118$#F70*>$119$#F11\">\n      <ellipse cx=\"10\" cy=\"13\" rx=\"8\" ry=\"8\" style=\"fill: #EEE; stroke: #BBB;\" />\n    </g>\n  </g>\n  <text x=\"2\" y=\"34\" fill=\"#666\" style=\"font-size:10px\">117</text>\n  <text x=\"192\" y=\"34\" fill=\"#666\" style=\"font-size:10px\">120</text>\n  <text x=\"54\" y=\"34\" fill=\"#666\" style=\"font-weight:bold;font-size:11px;\">AGA_AM_PRIORITY</text>\n</g>\n\n\n<!-- VERTICAL SLIDER -->\n<g transform=\"translate(140,120)\">\n  <path d=\"M28,10 l6,0 l0,200, l-6,0 z\" style=\" fill: #DDD; stroke: #BBB;\" />\n  <g isis_animation=\"translateY\" isis_ep=\"AGA_AM_PRIORITY\" isis_domain=\"117,120\" isis_width=\"200\" isis_direction=\"top\">\n    <g isis_animation=\"colour\" isis_ep=\"AGA_AM_PRIORITY\" isis_operators=\"<=$118$#EEE*>$118$#F70*>$119$#F11\">\n      <ellipse cx=\"31\" cy=\"210\" rx=\"8\" ry=\"8\" style=\"fill: #EEE; stroke: #BBB;\" />\n    </g>\n  </g>\n  <text x=\"0\" y=\"212\" fill=\"#666\" style=\"font-size:10px\">117</text>\n  <text x=\"0\" y=\"14\" fill=\"#666\" style=\"font-size:10px\">120</text>\n  <text x=\"14\" y=\"160\" fill=\"#666\" style=\"font-weight:bold;font-size:11px;\" transform=\"rotate(-90, 14, 160)\">AGA_AM_PRIORITY</text>\n</g>\n\n\n<!-- DIODE -->\n<g transform=\"translate(400,-880)\">\n  <path style=\"fill:#000;fill-rule:evenodd;stroke:#000;stroke-width:4;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none\" d=\"m 0.09962822,952.36218 59.19999778,0\" id=\"path3782\" />\n  <path id=\"path3788\" d=\"m 141.10364,952.36218 58.8264,0\" style=\"fill:#000;fill-rule:evenodd;stroke:#000;stroke-width:4;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none\" />\n  <path style=\"fill:#fff;stroke:#000000;stroke-width:3.99281930999999980;stroke-linejoin:round;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none\" id=\"path2998\" d=\"M 105.22681,50 63.8067,73.913909 22.386597,97.827818 l 0,-47.827819 0,-47.8278165 41.420106,23.9139095 z\"\n    transform=\"matrix(1,0,0,1.0036,38.749817,902.18218)\" />\n  <rect style=\"fill:#000;fill-opacity:1;stroke:#000;stroke-width:4;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none\" id=\"rect3016\" width=\"12.835206\" height=\"96\" x=\"145\" y=\"904.36218\" />\n</g>\n\n<!-- KNOBE -->\n<g transform=\"translate(220,200)\">\n  <circle r=\"80\" cx=\"100\" cy=\"100\" stroke=\"#FDE47F\" transform=\"rotate(126, 100, 100)\" stroke-width=\"10\" fill=\"none\" stroke-dasharray=\"402\"></circle>\n  <g isis_animation='rotate' isis_ep='AGA_AM_PRIORITY' isis_domain='117,121' isis_angle='292' isis_center='100,100'>\n    <path d=\"M100,30 l6,70 q-6,6 -12,0 z\" style=\"fill: #666\" transform=\"rotate(-146, 100, 100)\" />\n  </g>\n  <text x=\"50\" y=\"130\" fill=\"#999\" style=\"font-weight:bold;font-size:11px;\">AGA_AM_PRIORITY</text>\n  <text x=\"14\" y=\"170\" fill=\"#999\" style=\"font-weight:bold;font-size:11px\">117</text>\n  <text x=\"92\" y=\"8\" fill=\"#999\" style=\"font-weight:bold;font-size:11px\">119</text>\n  <text x=\"168\" y=\"170\" fill=\"#999\" style=\"font-weight:bold;font-size:11px\">121</text>\n</g>\n\n<!-- DIGITAL DISPLAY -->\n<g transform=\"translate(30,320)\">\n  <g isis_x=\"0\" isis_y=\"0\" isis_animation=\"textBox\" isis_ep=\"AGA_AM_PRIORITY\" isis_textcolor=\"0$#0C0;119$#E00\" isis_font=\"Digital\" isis_size=\"64px\">-</g>\n</g>\n\n<!-- TEXT BOX -->\n<g transform=\"translate(30,350\">\n  <g isis_x=\"0\" isis_y=\"0\" isis_animation=\"textBox\" isis_ep=\"AGA_AM_PRIOR_MS\" isis_size=\"20\">-</g>\n</g>\n",
  "entryPoints": [
    {
      "name": "TMMGT_BC_VIRTCHAN3",
      "connectedData": {
        "formula": "Reporting.TMMGT_BC_VIRTCHAN3<ReportingParameter>.extractedValue",
        "unit": "V",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1"
      }
    },
    {
      "name": "AGA_AM_PRIORITY",
      "connectedData": {
        "formula": "Reporting.AGA_AM_PRIORITY<ReportingParameter>.extractedValue",
        "unit": "V",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1"
      }
    },
    {
      "name": "AGA_AM_PRIOR_MS",
      "connectedData": {
        "formula": "Reporting.AGA_AM_PRIORITY<ReportingParameter>.monitoringState",
        "unit": "",
        "digits": 5,
        "format": "decimal",
        "filter": [],
        "domain": "fr.cnes.isis.simupus",
        "timeline": "Session 1"
      }
    }
  ]
}
